### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by raratiru** [jhildenbiddle/vertical-rhythm-reset#25]
```
    LibSass 3.2+
    Ruby Sass 3.4+
```
The libraries are deprecated. (https://sass-lang.com/blog/libsass-is-deprecated, https://sass-lang.com/ruby-sass)

Using the dependencies in this repository with latest LTS node (gallium):

https://github.com/jhildenbiddle/vertical-rhythm-reset/blob/f9cef25a25994c52b8b63f64a784e4368d3ad5c5/package.json#L41-L48

> 13 vulnerabilities (4 moderate, 9 high)

Is it fruitful to hope for a project update?

**Comment by jhildenbiddle** [comment]
Hi @raratiru --

Version 2 has been released with updated dependencies including Dart Sass support.

- https://jhildenbiddle.github.io/vertical-rhythm-reset/

**Comment by raratiru** [comment]
Thank you, this is great news!
